stages:
  - "build"
  - "test"
  - "release"
  - "deploy"
  - "operate"
  - "monitor"

build-java-8:
  script: echo "Build Java 8"
  stage: build
  tags:
    - claude

build-java-9:
  script: echo "Build Java 9"
  stage: build
  tags:
    - claude

build-java-20:
  script: 
    - echo "Build Java 20"
    - exit 2
  stage: build
  allow_failure: true
  tags:
    - claude

test-unit:
  script: echo "run unit test"
  stage: test
  tags:
    - claude

test-integration:
  script: echo "run integration test"
  stage: test
  tags:
    - claude

